### PR TITLE
fix fired eventhandler, use r_string without reference

### PR DESCRIPTION
**Pull request by mr-guard**
(VS changed to windows line endings)

### CODE REVIEW

**Comment by dedmen** [comment]
Do you want to turn this into a general update examples PR?
Need to update https://github.com/intercept/intercept/blob/master/src/host/common/easyloggingc%2B%2B.hpp and probably most of the eventhandlers also changed again.

**Comment by mr-guard** [comment]
Ok, I will try to do that next week

**Comment by dedmen** [comment]
🍪

**Comment by dedmen** [comment]
I totally don't know what's wrong with the Line endings here. It was CRLF before and it is CRLF now.
HAH! solved it! I don't know what I did tho. I'll merge this now and do the rest of the examples updates myself

**Pull request merged**
